### ISSUE TITLE
Notice of Copyright Violation

### ISSUE THREAD

**Issue by Iconoclasta** [ABPnetwork/ABP#1]
This is an official notice of Copyright violation against the PIVX developers in which this project has been forked from. The MIT copyright license, and subsequent copyright headers in source files have been modified to explicitely exclude the PIVX developers from all copyrights.

You are hereby notified of an intention to pursue further action if this issue is not acknowledged and formally addressed with a resolution timeframe commitment wherein. Failure to acknowledge and correct the violation will result in a formal DMCA takedown notice filed with GitHub Proper after no less than five business days from the date of this notice.

Explicit acknowledgement and referencing progress to maintain compliance MUST be noted in this issue's comments or referred to in any subsequent pull requests to this repository.

**Comment by ABPnetwork** [comment]
Thank you for referring this as an issue, however this has been fixed immediately.

The codebase has been updated 3 days ago to include the copyrights as you can see here:
https://github.com/ABPnetwork/ABP/commit/fe28bb26eedae78305281ace39b259d852daff5d

**Comment by Fuzzbawls** [comment]
this isn't completely resolved; still missing the essential copyright in https://github.com/ABPnetwork/ABP/blob/master/COPYING

**Comment by ABPnetwork** [comment]
This commit should solve the issue: https://github.com/ABPnetwork/ABP/commit/e73e7959d3ca49f9d5ace8d26cb2bfb082024a73

Thanks @Fuzzbawls for the help, indeed main copyright was missing.
We will close this issue in a day if there are no further inquiries.

**Comment by ABPnetwork** [comment]
No further comments, don't hesitate to open another issue if you find any other copyright violation, we're closing this one.
